### ISSUE TITLE
Use a YAML linter (**not** `prettier`)

### ISSUE THREAD

**Issue by QuintinWillison** [ably/features#37]
I've removed Prettier in #36.
It's presents more problems than it solves.

**Comment by surminus** [comment]
In the past I've used [yamllint](https://github.com/adrienverge/yamllint).

In the infrastructure repository I actually just [wrote my own](https://github.com/ably/infrastructure/blob/dbb33e890c7588512ae909c29c1bdfd7f003f758/Rakefile#L11-L29), because all I cared about was that the YAML was valid and could be loaded by a strict parser.
